# IMPLEMENTATION OF ARRAY 

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])


In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
type(arr)


numpy.ndarray

In [5]:
arr.shape

(5,)

In [6]:
arr.ndim

1

# Indexing on array

In [7]:
arr[0]

1

In [8]:
arr[3]


4

# Slicing on array


In [9]:
arr[0:]

array([1, 2, 3, 4, 5])

In [10]:
arr[0:5]

array([1, 2, 3, 4, 5])

In [11]:
arr[0:5:2]


array([1, 3, 5])

In [12]:
arr[-1]

5

In [13]:
arr[::-1]


array([5, 4, 3, 2, 1])

In [14]:
arr[-1::-1]


array([5, 4, 3, 2, 1])

In [15]:
arr[2:-1]


array([3, 4])

In [16]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])

In [17]:
arr1.shape


(2, 4)

In [18]:
arr1.ndim

2

In [19]:
arr2 = np.array([[10,20,30,40],[50,60,70,80]])


In [20]:
arr2.shape

(2, 4)

In [21]:
arr2.ndim

2

# Arithmetic Operations

In [22]:
arr1+arr2

array([[11, 22, 33, 44],
       [55, 66, 77, 88]])

In [23]:
arr1-arr2


array([[ -9, -18, -27, -36],
       [-45, -54, -63, -72]])

In [24]:
arr1*arr2

array([[ 10,  40,  90, 160],
       [250, 360, 490, 640]])

In [25]:
arr2/arr1

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.]])

# Reshape array


In [26]:
arr1.reshape(4,2)


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [27]:
arr1.reshape(1,8)


array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [28]:
arr1.reshape(8,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [29]:
arr1.flatten()


array([1, 2, 3, 4, 5, 6, 7, 8])

# Concatenate array

In [30]:
np.concatenate((arr1,arr2),axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 20, 30, 40],
       [50, 60, 70, 80]])

In [31]:
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  2,  3,  4, 10, 20, 30, 40],
       [ 5,  6,  7,  8, 50, 60, 70, 80]])

# Searching array

In [32]:
#search array using where 
arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr==4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [36]:
arr=np.array([1,2,3,4,5,6,7,8])
x = np.where(arr%2==0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [38]:
#searchsorted
arr=np.array([6,8,9])
x = np.searchsorted(arr,7)
print(x)

1


In [39]:
arr = np.array([1,3,5,7])
x = np.searchsorted(arr,[2,4,6])
print(x)

[1 2 3]


# stacking

In [41]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1,arr2),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


# Concatenate

In [42]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr =  np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


# Splitting Array

In [43]:
arr = np.array([1,2,3,4,5,6])
newarr =  np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
