# Universal Functions

In [1]:
import numpy as np

# Arithmetic Functions

In [2]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

In [3]:
#addition
result=np.add(a,b)
print("Addition using universal function : ",result)
#subtraction
result1=np.subtract(a,b)
print("Subtraction using universal function : ",result1)
#multiplication
result2=np.multiply(a,b)
print("Multiplication using universal function : ",result2)
#Divide
result3=np.divide(a,b)
print("division using universal function : ",result3)


Addition using universal function :  [ 7  9 11 13 15]
Subtraction using universal function :  [-5 -5 -5 -5 -5]
Multiplication using universal function :  [ 6 14 24 36 50]
division using universal function :  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


# Statistical function

In [4]:
marks = np.array([60, 91, 80, 88, 69, 73, 49, 75]) 
# minimum and maximum 
print('Minimum and maximum marks of the students: ') 
print(np.amin(marks), np.amax(marks)) 
# range of marks i.e. max weight-min weight 
print('Range of the marks of the students: ') 
print(np.ptp(marks)) 
# percentile 
print('marks below which 70 % student fall: ') 
print(np.percentile(marks, 70)) 
# mean 
print('Mean marks of the students: ') 
print(np.mean(marks)) 
# median 
print('Median marks of the students: ') 
print(np.median(marks)) 
# standard deviation 
print('Standard deviation of marks of the students: ') 
print(np.std(marks)) 
# variance 
print('Variance of marks of the students: ') 
print(np.var(marks)) 
# average 
print('Average marks of the students: ') 
print(np.average(marks))


Minimum and maximum marks of the students: 
49 91
Range of the marks of the students: 
42
marks below which 70 % student fall: 
79.5
Mean marks of the students: 
73.125
Median marks of the students: 
74.0
Standard deviation of marks of the students: 
13.052178936867207
Variance of marks of the students: 
170.359375
Average marks of the students: 
73.125


# Trigonometric functions

In [5]:
# create an array of angles 
angles = np.array([0, 30, 45, 60, 90, 180]) 


In [6]:
# conversion of degree into radians 
# using deg2rad function 
radians = np.deg2rad(angles) 
# sine of angles 
print('Sine of angles in the array:') 
sine_value = np.sin(radians) 
print(np.sin(radians)) 
# inverse sine of sine values 
print('Inverse Sine of sine values:') 
print(np.rad2deg(np.arcsin(sine_value))) 
# hyperbolic sine of angles 
print('Sine hyperbolic of angles in the array:') 
sineh_value = np.sinh(radians) 
print(np.sinh(radians)) 
# inverse sine hyperbolic 
print('Inverse Sine hyperbolic:') 
print(np.sin(sineh_value)) 
# hypot function demonstration 
base = 4
height = 3
print('hypotenuse of right triangle is:') 
print(np.hypot(base, height))

Sine of angles in the array:
[0.00000000e+00 5.00000000e-01 7.07106781e-01 8.66025404e-01
 1.00000000e+00 1.22464680e-16]
Inverse Sine of sine values:
[0.0000000e+00 3.0000000e+01 4.5000000e+01 6.0000000e+01 9.0000000e+01
 7.0167093e-15]
Sine hyperbolic of angles in the array:
[ 0.          0.54785347  0.86867096  1.24936705  2.3012989  11.54873936]
Inverse Sine hyperbolic:
[ 0.          0.52085606  0.76347126  0.94878485  0.74483916 -0.85086591]
hypotenuse of right triangle is:
5.0


# Comparison functions

In [7]:
#greater
a = np.array([4,2])
b = np.array([2,2])
a > b
#greater
np.greater([4, 2, 1], [2, 2, 2])


array([ True, False, False])

In [8]:
#greater_equal
np.greater_equal([4, 2, 1], [2, 2, 2])

array([ True,  True, False])

In [9]:
#less
np.less([1, 2], [2, 2])


array([ True, False])

In [10]:
#less_equal
np.less_equal([4, 2, 1], [2, 2, 2])


array([False,  True,  True])

In [11]:
#not_equal 
np.not_equal([1.,2.], [1., 3.])
np.not_equal([1, 2], [[1, 3],[1, 4]])

array([[False,  True],
       [False,  True]])

In [12]:
#equal
np.equal([0, 1, 3], np.arange(3))
np.equal(1, np.ones(1))

array([ True])

# Logical functions


# Logical AND


In [13]:
#LOGICAL AND
np.logical_and(True, False)

False

In [14]:
np.logical_and([True, False], [False, False])


array([False, False])

# Logical OR

In [15]:
#LOGICAL OR
np.logical_or(True, False)

True

In [16]:
x = np.arange(5)
np.logical_or(x < 1, x > 3)


array([ True, False, False, False,  True])

# Logical XOR

In [17]:
#LOGICAL XOR
np.logical_xor(True, False)


True

In [18]:
x = np.arange(5)
np.logical_xor(x < 1, x > 3)

array([ True, False, False, False,  True])

# Logical NOT

In [19]:
#LOGICAL NOT
np.logical_not(3)


False

In [20]:
np.logical_not([True, False, 0, 1])


array([False,  True,  True, False])

In [21]:
x = np.arange(5)
np.logical_not(x<3)

array([False, False, False,  True,  True])

# Floating functions

In [22]:
np.isreal([1+1j, 1+0j, 4.5, 3, 2, 2j])


array([False,  True,  True,  True,  True, False])

In [23]:
np.iscomplex([1+1j, 1+0j, 4.5, 3, 2, 2j])

array([ True, False, False, False, False,  True])

In [24]:
np.isfinite(1)


True

In [25]:
np.isfinite(0)

True

In [26]:
np.isnan(np.nan)

True

In [27]:
np.modf(-0.5)


(-0.5, -0.0)

In [28]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.trunc(a)

array([-1., -1., -0.,  0.,  1.,  1.,  2.])